language: java
jdk:
- oraclejdk14

script: ant clean
script: ant compile
script: ant jar
script: ant junit

before_script:
   - sudo apt-get install ant-optional

addons:
  sonarcloud:
    organization: "adrchacon"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
